# Generated by Django 5.1.3 on 2024-11-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="students",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="students",
            name="course_code",
        ),
        migrations.RemoveField(
            model_name="students",
            name="enrollment_date",
        ),
    ]
