# Generated by Django 5.1.3 on 2024-11-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_classes_class_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="class_number",
        ),
    ]
