# Generated by Django 5.1.3 on 2024-11-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_remove_classes_class_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="class_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateField(),
        ),
    ]
