# Generated by Django 5.1.3 on 2024-11-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
